#!/bin/bash
OPTIONS="Hello Kiss Quit"
select opt in $OPTIONS; do
   if [ "$opt" = "Quit" ]; then
    echo done
    exit
   elif [ "$opt" = "Hello" ]; then
    echo Hello World
   elif [ "$opt" = "Kiss" ]; then
   	echo "Kiss :* :*"
   else
    clear
    echo bad option
   fi
done
